name: Container Build Test

on:
  push:
    tags: [ "v*" ]
  pull_request:
    branches: [ master, main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Build Container
      run: docker build -t ${{ env.IMAGE_NAME }} -f Containerfile .
